package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
)

type AutoGenerated []struct {
	IP        string `json:"ip"`
	Timestamp string `json:"timestamp"`
	Ports     []struct {
		Port   int    `json:"port"`
		Proto  string `json:"proto"`
		Status string `json:"status"`
		Reason string `json:"reason"`
		TTL    int    `json:"ttl"`
	} `json:"ports"`
	ID int `json:"id"`
}

func main() {

	data, err := ioutil.ReadFile("./ipss.json")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("data type: %T\n", data)

	//ips := []Ip{}
	var ips AutoGenerated

	err2 := json.Unmarshal(data, &ips)

	if err2 != nil {
		fmt.Println(err2)
	}

	fmt.Println(len(ips))
	for i:=0; i<len(ips); i++{
		fmt.Println(ips[i].IP,":",ips[i].Ports[0].Port)
	}

}
